name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install apt dependencies
        run: sudo apt install bcftools htslib

      - name: Install Python dependencies
        run: python -m pip install requirements-dev.txt

      - name: Package installation
        run: pip install .

      - name: Run tests (Windows)
        run: python -m pytest
